# Site settings
title: Arghya Sadhu
email: arghya88@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my blog site where I share my experience as a Software Developer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://arghya88.github.io" # the base hostname & protocol for your site
twitter_username: arghya88
github_username:  arghya88

# Build settings
markdown: kramdown
highlighter: pygments

prose:
  rooturl: '_posts'
  siteurl: 'http://arghya88.github.io'
